env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - "tsconfig.json"
plugins:
  - react
settings:
  react:
    version: detect
rules: {}
